# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

# -----------------------kinova------------------------------------
finger_1_position_controller:
  joint: j2n6s300_joint_finger_1
  pid:
    d: 0
    i: 0
    p: 10
  type: effort_controllers/JointPositionController
finger_2_position_controller:
  joint: j2n6s300_joint_finger_2
  pid:
    d: 0
    i: 0
    p: 10
  type: effort_controllers/JointPositionController
finger_3_position_controller:
  joint: j2n6s300_joint_finger_3
  pid:
    d: 0
    i: 0
    p: 10
  type: effort_controllers/JointPositionController
finger_tip_1_position_controller:
  joint: j2n6s300_joint_finger_tip_1
  pid:
    d: 0
    i: 0
    p: 0.5
  type: effort_controllers/JointPositionController
finger_tip_2_position_controller:
  joint: j2n6s300_joint_finger_tip_2
  pid:
    d: 0
    i: 0
    p: 0.5
  type: effort_controllers/JointPositionController
finger_tip_3_position_controller:
  joint: j2n6s300_joint_finger_tip_3
  pid:
    d: 0
    i: 0
    p: 0.5
  type: effort_controllers/JointPositionController
joint_1_position_controller:
  joint: j2n6s300_joint_1
  pid:
    d: 8.0
    i: 0
    p: 5000
  type: effort_controllers/JointPositionController
joint_2_position_controller:
  joint: j2n6s300_joint_2
  pid:
    d: 8.0
    i: 0
    p: 5000
  type: effort_controllers/JointPositionController
joint_3_position_controller:
  joint: j2n6s300_joint_3
  pid:
    d: 8.0
    i: 0
    p: 5000
  type: effort_controllers/JointPositionController
joint_4_position_controller:
  joint: j2n6s300_joint_4
  pid:
    d: 0.2
    i: 0
    p: 500
  type: effort_controllers/JointPositionController
joint_5_position_controller:
  joint: j2n6s300_joint_5
  pid:
    d: 0.2 # 5.0
    i: 0
    p: 2000 # 500
  type: effort_controllers/JointPositionController
joint_6_position_controller:
  joint: j2n6s300_joint_6
  pid:
    d: 0
    i: 0
    p: 500
  type: effort_controllers/JointPositionController